# Generated by Django 4.1.3 on 2025-05-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('future', 'Future'), ('client', 'Client'), ('general', 'General')], max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe'), ('es', 'Español'), ('bg', 'Български')], max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
        ),
    ]
