# Generated by Django 4.1.3 on 2025-05-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('language', models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe'), ('es', 'Español'), ('bg', 'Български')], max_length=2)),
                ('category', models.CharField(choices=[('general', 'General'), ('data', 'Data Analysis'), ('web', 'Web Development'), ('python', 'Python Development'), ('ai', 'Artificial Intelligence'), ('cases', 'User Cases'), ('training', 'Training')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
