# Generated by Django 4.1.3 on 2025-05-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe'), ('es', 'Español'), ('bg', 'Български')], max_length=2)),
                ('content_preview', models.TextField(help_text='Blog yazısının kısa özeti veya giriş kısmı')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='blog_thumbnails/')),
                ('published_at', models.DateField()),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
    ]
