# Generated by Django 4.1.3 on 2025-05-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon', models.CharField(help_text='FontAwesome sınıf adı örn: fa-brands fa-instagram', max_length=100)),
                ('language', models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe'), ('es', 'Español'), ('bg', 'Български')], max_length=2)),
            ],
            options={
                'verbose_name': 'Sosyal Medya Bağlantısı',
                'verbose_name_plural': 'Sosyal Medya Bağlantıları',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='team/')),
                ('language', models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe'), ('es', 'Español'), ('bg', 'Български')], max_length=2)),
            ],
            options={
                'verbose_name': 'Ekip Üyesi',
                'verbose_name_plural': 'Ekip Üyeleri',
            },
        ),
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_key', models.CharField(help_text='sayfa anahtarı: örnek -> aboutus, ourvision, ourmission', max_length=50)),
                ('language', models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe'), ('es', 'Español'), ('bg', 'Български')], max_length=2)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='page_images/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayfa İçeriği',
                'verbose_name_plural': 'Sayfa İçerikleri',
                'unique_together': {('page_key', 'language')},
            },
        ),
    ]
