# Generated by Django 4.1.3 on 2025-05-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('tr', 'Türkçe'), ('es', 'Español'), ('bg', 'Български')], max_length=2)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('map_embed', models.TextField(blank=True, help_text='Google Maps iframe embed kodu', null=True)),
            ],
        ),
    ]
